version: '3.2'

services:
  docs-watch:
    build:
      dockerfile: ./docker/docs-watch/Dockerfile
      context: .
    volumes:
      - ./schema:/app/src/schema:cached
    command: yarn run start

  mock-server:
    build:
      dockerfile: ./docker/mock-server/Dockerfile
      context: .
    labels:
      - specs-mock-server=""
    ports:
      - 8080:8080
    volumes:
      - ./schema:/app/openrpc:cached

  openrpc-validator:
    build:
      dockerfile: ./docker/openrpc-validator/Dockerfile
      context: .
    volumes:
      - ./schema:/home/node/schema:cached
